spring:
  datasource:
    url: ${env.POSTGRES_URL}
    username: ${env.POSTGRES_USERNAME}
    password: ${env.POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        current_session_context_class: thread

jwt:
  token:
    secret: ${env.JWT_SECRET}
    expires: 86400000
    expire-multiplier: 4

amazon:
  s3:
    access-key: ${env.AWS_ACCESS_KEY_ID}
    bucket-name: ${env.AWS_BUCKET_NAME}
    region: ${env.AWS_REGION}
    secret-key: ${env.AWS_SECRET_ACCESS_KEY}

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE

